remote_theme: pages-themes/cayman@v0
plugins:
  - jekyll-remote-theme
title: Advanced Auto Brightness
description: A Tasker project that dynamically adjusts Android screen brightness.
show_downloads: true
