name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package artifacts
        run: |
          cd tasker
          zip -9 ../Advanced-Auto-Brightness.prj.zip Advanced-Auto-Brightness.prj.xml
          cd ..
          sha256sum tasker/Advanced-Auto-Brightness.prj.xml > SHA256SUMS.txt
          sha256sum Advanced-Auto-Brightness.prj.zip >> SHA256SUMS.txt
      - name: Create GitHub Release and upload Tasker project
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tasker/Advanced-Auto-Brightness.prj.xml
            Advanced-Auto-Brightness.prj.zip
            SHA256SUMS.txt
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
